#!/usr/bin/env bash

# NOTE THAT THIS WAS GENERATED BY AI BASED ON THE RUN.BAT FILE. THIS MAY NOT WORK PROPERLY.
echo "NOTE THAT THIS WAS GENERATED BY AI BASED ON THE RUN.BAT FILE. THIS MAY NOT WORK PROPERLY."

# Get script directory (equivalent to %~dp0)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

VENV_DIR="$SCRIPT_DIR/.venv"
PYTHON="$VENV_DIR/bin/python"

# Create virtual environment if it doesn't exist
if [ ! -f "$PYTHON" ]; then
    echo "Creating virtual environment..."
    python3 -m venv "$VENV_DIR"
fi

# Activate virtual environment
source "$VENV_DIR/bin/activate"

# Upgrade pip and install dependencies
python -m pip install --upgrade pip
python -m pip install -r "$SCRIPT_DIR/requirements.txt"

echo "Dependencies installed."

# Run main script
python "$SCRIPT_DIR/main.py"

# Optional pause (like Windows 'pause')
read -p "Press Enter to continue..."
